---
title: "Gramática de Gráficos"
output: pdf_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Introducir Datos

```{r}
library(ggplot2)
library(palmerpenguins)

ggplot(data = penguins) # data = tabla de datos de entrada
```

### Introducir Estética (aesthetic)

```{r}
ggplot(data = penguins,
       # con la función aes() se definen las propiedades estéticas
       aes(x = bill_length_mm, y = bill_depth_mm))
```

### Introducir objeto geométrico

```{r message=FALSE, warning=FALSE}
ggplot(data = penguins,
       aes(x = bill_length_mm, y = bill_depth_mm)) +
  # geom_point() para generar una figura de dispersión de puntos
  geom_point()
```

### Combinar varios objetos geométricos

```{r message=FALSE, warning=FALSE}
ggplot(data = penguins, 
       aes(x = bill_length_mm, y = bill_depth_mm)) +
  # podemos añadir varios objetos geométricos que se combinan en una misma figura
  geom_point() +
  geom_line()
```

### Cambiar las propiedades de un objeto

```{r message=FALSE, warning=FALSE}
ggplot(data = penguins,
       aes(x = bill_length_mm, y = bill_depth_mm)) +
  # los objetos geométricos tienen una serie de propiedades que podemos cambiar
  geom_point(size = 2, # tamaño 
             color = "deepskyblue3", # color
             shape = "square") + # forma
  geom_line(color = "orange", # color 
            linetype = "dotted", # tipo de línea
            linewidth = 0.8) # tamaño de la línea
```

